name: Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Set-up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Set-up latest pip
      run: |
        python -m pip install --upgrade pip

    - name: Cache Conan directory
      id: cache-conan
      uses: actions/cache@v1
      with:
        path: ~/.conan
        key: ${{ runner.os }}-conan
        restore-keys: |
          ${{ runner.os }}-conan

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: pip cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-1
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set-up conan
      run: |
        pip install --upgrade conan

    - name: Install linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          zlib1g-dev \
          libfontconfig1-dev \
          libmpg123-dev \
          libsndfile1 \
          libsndfile1-dev \
          libpulse-dev \
          libasound2-dev \
          libcurl4-gnutls-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          gstreamer1.0-libav \
          gstreamer1.0-alsa \
          gstreamer1.0-pulseaudio \
          gstreamer1.0-plugins-bad

    - name: Create the package
      env:
        PACKAGE_USER: yamadapc
        PACKAGE_CHANNEL: stable
      run: |
        conan create -tf None -s cppstd=17 -s build_type=Release $GITHUB_WORKSPACE $PACKAGE_USER/$PACKAGE_CHANNEL

    - name: Upload the package
      env:
        BINTRAY_URL: https://api.bintray.com/conan/yamadapc/yamadapc_conan
        BINTRAY_REPOSITORY: yamadapc_conan
        BINTRAY_TOKEN: ${{ secrets.BINTRAY_TOKEN }}
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      run: |
        conan remote add $BINTRAY_REPOSITORY $BINTRAY_URL
        conan user -p $BINTRAY_TOKEN -r $BINTRAY_REPOSITORY $BINTRAY_USER
        conan upload --all -r yamadapc_conan "cinder/*@yamadapc/*"
