name: Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set-up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Set-up conan
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade conan
    - name: Create the package
      run: |
        conan create $GITHUB_WORKSPACE $PACKAGE_USER/$PACKAGE_CHANNEL
    - name: Upload the package
      run: |
        conan remote add $BINTRAY_REPOSITORY $BINTRAY_URL
        conan user -p $BINTRAY_TOKEN -r $BINTRAY_REPOSITORY $BINTRAY_USER
